name: flutter_i18n_extractor
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  analyzer: ^6.4.1
  yaml: ^3.1.2
  crypto: any
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
